server:
  port: 8088

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##java
    password: 123
  messages:
    basename: messages
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

logging:
  level:
    org.springframework: DEBUG